# Generated by Django 4.0 on 2022-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('sample_date', models.DateField()),
                ('total_vaccinations', models.FloatField(blank=True, null=True, verbose_name='Tot. Vax')),
                ('people_vaccinated', models.FloatField(blank=True, null=True, verbose_name='People Vax')),
                ('people_vaccinated_per_hundred', models.FloatField(blank=True, null=True, verbose_name='Vax 1 %')),
                ('people_fully_vaccinated', models.FloatField(blank=True, null=True, verbose_name='People Vax 2')),
                ('people_fully_vaccinated_per_hundred', models.FloatField(blank=True, null=True, verbose_name='Vax 2 %')),
                ('total_vaccinations_per_hundred', models.FloatField(blank=True, null=True, verbose_name='Total Vax %')),
                ('total_boosters', models.FloatField(blank=True, null=True, verbose_name='Boosters')),
                ('total_boosters_per_hundred', models.FloatField(blank=True, null=True, verbose_name='Boosters %')),
            ],
        ),
    ]
