# Generated by Django 4.0 on 2022-10-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usvaccination',
            options={'verbose_name': 'Vaccination (US)', 'verbose_name_plural': 'Vaccinations (US)'},
        ),
    ]
