# Generated by Django 4.1.3 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DIVOCCase7DayAvg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                ("case_date", models.DateField()),
                (
                    "cases",
                    models.FloatField(
                        help_text="cases per 100k, 7d average", verbose_name="Cases"
                    ),
                ),
                (
                    "peak",
                    models.FloatField(blank=True, null=True, verbose_name="Peak Value"),
                ),
                (
                    "iscore",
                    models.FloatField(blank=True, null=True, verbose_name="IScore"),
                ),
                (
                    "iscore_raw",
                    models.FloatField(blank=True, null=True, verbose_name="Raw IScore"),
                ),
                (
                    "rscore",
                    models.FloatField(blank=True, null=True, verbose_name="RScore"),
                ),
                (
                    "vscore",
                    models.FloatField(blank=True, null=True, verbose_name="VScore"),
                ),
                (
                    "nscore",
                    models.FloatField(blank=True, null=True, verbose_name="NScore"),
                ),
            ],
            options={
                "verbose_name": "DIVOC Case (7d)",
                "verbose_name_plural": "DIVOC Cases (7d)",
            },
        ),
        migrations.CreateModel(
            name="DIVOCCaseDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                ("case_date", models.DateField()),
                (
                    "cases",
                    models.FloatField(
                        help_text="cases per 100k, 7d average", verbose_name="Cases"
                    ),
                ),
                (
                    "peak",
                    models.FloatField(blank=True, null=True, verbose_name="Peak Value"),
                ),
            ],
            options={
                "verbose_name": "DIVOC Case Daily",
                "verbose_name_plural": "DIVOC Cases Daily",
            },
        ),
        migrations.CreateModel(
            name="DIVOCCaseTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                ("case_date", models.DateField()),
                (
                    "cases",
                    models.FloatField(
                        help_text="cases per 100k, 7d average", verbose_name="Cases"
                    ),
                ),
            ],
            options={
                "verbose_name": "DIVOC Case Total",
                "verbose_name_plural": "DIVOC Cases Total",
            },
        ),
    ]
