# Generated by Django 4.0 on 2022-10-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIVOCCase7DayAvg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('case_date', models.DateField()),
                ('cases', models.FloatField(help_text='cases per 100k, 7d average', verbose_name='Cases')),
            ],
            options={
                'verbose_name': 'DIVOC Case (7d)',
                'verbose_name_plural': 'DIVOC Cases (7d)',
            },
        ),
        migrations.CreateModel(
            name='DIVOCCaseTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'DIVOC Case Total',
                'verbose_name_plural': 'DIVOC Cases Total',
            },
        ),
    ]
