# Generated by Django 4.0 on 2022-10-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divoccasetotal',
            name='case_date',
            field=models.DateField(default='2022-11-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divoccasetotal',
            name='cases',
            field=models.FloatField(default=0, help_text='cases per 100k, 7d average', verbose_name='Cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divoccasetotal',
            name='location',
            field=models.CharField(default='test', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
